const config = {
   port: 3000,
   games: [{
      name: 'poki',
      url: 'https://www.poki.com'
   }, {
      name: 'unblocked-games-77',
      url: 'https://www.unblocked-games-77.com'
   }, {
      name: 'unblocked-games-66',
      url: 'https://www.unblocked-games-66.com'
   }, {
      name: 'coolmath-games',
      url: 'https://www.coolmathgames.com'
   }, {
      name: 'unblocked-games-24',
      url: 'https://www.unblocked-games-24.com'
   }, {
      name: 'armor-games',
      url: 'https://www.armorgames.com'
   }, {
      name: 'kongregate',
      url: 'https://www.kongregate.com'
   }, {
      name: 'addictinggames',
      url: 'https://www.addictinggames.com'
   }, {
      name: 'unblocked-games-333',
      url: 'https://www.unblocked-games-333.com'
   }, {
      name: 'y8',
      url: 'https://www.y8.com'
   }, {
      name: 'agar-io',
      url: 'https://www.agar.io'
   }, {
      name: 'slither-io',
      url: 'https://www.slither.io'
   }, {
      name: 'diep-io',
      url: 'https://www.diep.io'
   }, {
      name: 'krunker-io',
      url: 'https://www.krunker.io'
   }, {
      name: 'geoguessr',
      url: 'https://www.geoguessr.com'
   }, ],
};
module.exports = config;
